name: Build Assembly Tool
on:
  workflow_dispatch:
    inputs:
      tool_name:
        description: 'Tên thư mục tool trong assembly/'
        required: true
        default: '_template'

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Compile and Link Assembly (Extreme Optimized)
        working-directory: assembly/${{ github.event.inputs.tool_name }}
        run: |
          # 1. Biên dịch ASM thành .obj
          ml64.exe /c /Cx /W3 main.asm
          
          # 2. Liên kết siêu nén (Super Compression Link)
          # - Chỉ dùng kernel32.lib
          # - Trộn (.MERGE) các phân vùng Data và Text lại để tiết kiệm khoảng trống của Header
          link.exe main.obj /SUBSYSTEM:CONSOLE /MACHINE:X64 /ENTRY:main /MERGE:.rdata=.text /MERGE:.pdata=.text /OUT:"${{ github.event.inputs.tool_name }}.exe" kernel32.lib
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.tool_name }}_asm_amd64.exe
          path: assembly/${{ github.event.inputs.tool_name }}/${{ github.event.inputs.tool_name }}.exe
