name: Build Zig Tool
on:
  workflow_dispatch:
    inputs:
      tool_name:
        description: 'Tên thư mục tool trong zig/'
        required: true
        default: '_template'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig 0.13.0
        uses: mlugg/setup-zig@v1
        with:
          version: '0.13.0'
      - name: Build and Rename EXE
        working-directory: zig/${{ github.event.inputs.tool_name }}
        run: |
          zig build -Doptimize=ReleaseSmall
          Get-ChildItem zig-out\bin\*.exe | Rename-Item -NewName "${{ github.event.inputs.tool_name }}.exe"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.tool_name }}_zig_amd64.exe
          path: zig/${{ github.event.inputs.tool_name }}/zig-out/bin/${{ github.event.inputs.tool_name }}.exe
